"""Add receipt number to payments

Revision ID: 2abe18bbeb75
Revises: 8a6f86e80a1c
Create Date: 2026-07-01 11:41:51.030561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2abe18bbeb75'
down_revision: Union[str, Sequence[str], None] = '8a6f86e80a1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('receipt_number', sa.String(), nullable=True))
    op.create_index(op.f('ix_payments_receipt_number'), 'payments', ['receipt_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_receipt_number'), table_name='payments')
    op.drop_column('payments', 'receipt_number')
    # ### end Alembic commands ###
