"""Add last_billed_date to tenants

Revision ID: 406889b57af7
Revises: 12d1aee47d8e
Create Date: 2026-06-29 14:52:10.240059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '406889b57af7'
down_revision: Union[str, Sequence[str], None] = '12d1aee47d8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('last_billed_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'last_billed_date')
    # ### end Alembic commands ###
