"""Add payment method and transaction reference

Revision ID: 512fbb6dac32
Revises: 2abe18bbeb75
Create Date: 2026-07-01 14:45:09.229556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '512fbb6dac32'
down_revision: Union[str, Sequence[str], None] = '2abe18bbeb75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('payment_method', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('transaction_reference', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'notes')
    op.drop_column('payments', 'transaction_reference')
    op.drop_column('payments', 'payment_method')
    # ### end Alembic commands ###
