"""Add lease fields to tenant

Revision ID: 61a692d6bea3
Revises: 406889b57af7
Create Date: 2026-06-30 13:19:26.415551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61a692d6bea3'
down_revision: Union[str, Sequence[str], None] = '406889b57af7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('lease_start', sa.Date(), nullable=True))
    op.add_column('tenants', sa.Column('lease_end', sa.Date(), nullable=True))
    op.add_column('tenants', sa.Column('deposit', sa.Float(), nullable=True))
    op.add_column('tenants', sa.Column('lease_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'lease_status')
    op.drop_column('tenants', 'deposit')
    op.drop_column('tenants', 'lease_end')
    op.drop_column('tenants', 'lease_start')
    # ### end Alembic commands ###
