"""Add checkout date

Revision ID: e1f958f89abf
Revises: 61a692d6bea3
Create Date: 2026-06-30 14:41:44.092422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1f958f89abf'
down_revision: Union[str, Sequence[str], None] = '61a692d6bea3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('checkout_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'checkout_date')
    # ### end Alembic commands ###
